# Compile, bundle, and upload application bundles
# to a cloud storage on each pull request to "main".
# https://help.github.com/actions

name: PR

on:
  pull_request:
    branches: [main]

env:
  CI: true
  VERSION: ${{ github.event.pull_request.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install

      # Analyze code for potential problems
      - run: yarn prettier --check .
      - run: yarn lint --no-cache
      - run: yarn tsc

      # Test
      # - run: yarn test

      # Compile
      - run: yarn build

      # Deploy
      # - run: yarn deploy
